# File: config/environments/production.yaml
# Production environment configuration

server:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  reload: false
  debug: false

frontend:
  port: 80
  build_dir: "dist"

cors:
  allow_origins:
    - "https://your-domain.com"
    - "https://www.your-domain.com"

ssl:
  enabled: true
  cert_file: "/etc/ssl/certs/juggler.crt"
  key_file: "/etc/ssl/private/juggler.key"
  redirect_http: true

providers:
  ollama:
    enabled: true
    base_url: "http://ollama:11434"  # Docker service name
    
  groq:
    enabled: true
    
  gemini:
    enabled: true
    
  openai:
    enabled: true

database:
  path: "/data/production/juggler.db"
  echo: false
  backup_enabled: true
  backup_interval: 86400  # Daily backups

logging:
  level: "INFO"
  file: "/var/log/juggler/juggler.log"
  console: false
  structured: true
  
security:
  secret_key: null  # Must be provided via environment
  session_lifetime: 43200  # 12 hours
  rate_limiting:
    enabled: true
    requests_per_minute: 30  # More restrictive
    burst_size: 5
  
  headers:
    x_frame_options: "DENY"
    x_content_type_options: "nosniff" 
    x_xss_protection: "1; mode=block"
    strict_transport_security: "max-age=31536000; includeSubDomains"

features:
  conversation_export: true
  parallel_queries: false  # Resource intensive
  context_transfer: true
  health_monitoring: true
  admin_dashboard: true

monitoring:
  health_check_interval: 60
  metrics_retention: 604800  # 7 days
  prometheus_enabled: true
  prometheus_port: 9090
  
performance:
  max_conversation_length: 100  # messages
  context_window_limit: 32768
  response_timeout: 120
  connection_pool_size: 20
  
backup:
  enabled: true
  schedule: "0 2 * * *"  # Daily at 2 AM
  retention_days: 30
  compression: true
  
alerts:
  email_enabled: false
  webhook_enabled: false
  error_threshold: 10  # errors per minute
  latency_threshold: 10000  # 10 seconds